**work-around** odd compiler error reported by MSVC (compiler bug?!?!?), as reported by MSVC2022 (latest):
options.test.cpp(29,3): error C7692: 'bool Term::Options::operator ==(const Term::Options &)': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
could be
    'bool Term::Options::operator ==(const Term::Options &)' [synthesized expression 'y == x']
  ==>
  'bool Term::Options::operator ==(const Term::Options &)': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
or
    'unknown-type doctest::detail::Expression_lhs<const Term::Options &>::operator ==(R &&)'
  ==>
  Failed to specialize function template 'unknown-type doctest::detail::Expression_lhs<const Term::Options &>::operator ==(R &&)'
  With the following template arguments:
    'R=Term::Options &'
    'bool Term::Options::operator ==(const Term::Options &)': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope

    could be
        'bool Term::Options::operator ==(const Term::Options &)'
      ==>
      'bool Term::Options::operator ==(const Term::Options &)': cannot convert 'this' pointer from 'const Term::Options' to 'Term::Options &'
      Conversion loses qualifiers
    or
        'bool doctest::operator ==(const doctest::Approx &,double)'
      ==>
      'bool doctest::operator ==(const doctest::Approx &,double)': cannot convert argument 1 from 'const Term::Options' to 'const doctest::Approx &'
      Reason: cannot convert from 'const Term::Options' to 'const doctest::Approx'
      No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    or
        'bool doctest::operator ==(double,const doctest::Approx &)'
      ==>
      'bool doctest::operator ==(double,const doctest::Approx &)': cannot convert argument 1 from 'const Term::Options' to 'double'
      No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    or
        'bool doctest::operator ==(const doctest::Contains &,const doctest::String &)'
      ==>
      'bool doctest::operator ==(const doctest::Contains &,const doctest::String &)': cannot convert argument 1 from 'const Term::Options' to 'const doctest::Contains &'
      Reason: cannot convert from 'const Term::Options' to 'const doctest::Contains'
      No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    or
        'bool doctest::operator ==(const doctest::String &,const doctest::Contains &)'
      ==>
      'bool doctest::operator ==(const doctest::String &,const doctest::Contains &)': cannot convert argument 1 from 'const Term::Options' to 'const doctest::String &'
      Reason: cannot convert from 'const Term::Options' to 'const doctest::String'
      No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    or
      'bool doctest::operator ==(const doctest::String &,const doctest::String &)'
      ==>
      'bool doctest::operator ==(const doctest::String &,const doctest::String &)': cannot convert argument 1 from 'const Term::Options' to 'const doctest::String &'
      Reason: cannot convert from 'const Term::Options' to 'const doctest::String'
      No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    or
        'bool Term::Options::operator ==(const Term::Options &)' [synthesized expression 'y == x']
      ==>
      'bool Term::Options::operator ==(const Term::Options &)': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
      while trying to match the argument list '(const Term::Options, Term::Options)'
  while trying to match the argument list '(doctest::detail::Expression_lhs<const Term::Options &>, Term::Options)'